/**
 * Polyfill for `.stringFormat()` generated by Orval but not available in Zod v4.
 * Must be imported (as a side-effect) before any generated api-zod modules.
 */
import * as zod from 'zod'

const proto = Object.getPrototypeOf(zod.email()) as Record<string, unknown>
if (typeof proto.stringFormat !== 'function') {
  proto.stringFormat = function () {
    return this
  }
}
