import { MutationCache, QueryCache, QueryClient } from '@tanstack/react-query'
import { isProblemDetails } from '@collana-solutions/blueprint-core'
import { showErrorNotification } from './show-error-notification'

export interface BlueprintQueryClientOptions {
    /**
     * Called for any query or mutation error that is not suppressed and is not a 401.
     * Defaults to the package's own Mantine notification.
     */
    onError?: (error: unknown) => void
    /** Retry attempts for a 5xx or network failure. Defaults to 2. */
    maxRetries?: number
}

/**
 * Builds a QueryClient wired for an ASP.NET backend returning RFC 9457 Problem Details.
 *
 * Error handling for hooks generated by Orval. Suppress per-call via
 * `meta: { suppressToast: true }` on useQuery / useMutation. For direct axios calls (not
 * hooks), use `__suppressToast: true` on the request config — see `augmentations.d.ts`
 * for the typed contract.
 *
 * A factory rather than a module-level singleton: a QueryClient exported from a package
 * would be shared across every consumer that resolved the same copy, and would silently
 * diverge for any consumer that resolved a second one.
 */
export function createBlueprintQueryClient(
    options?: BlueprintQueryClientOptions,
): QueryClient {
    const notify = options?.onError ?? showErrorNotification
    const maxRetries = options?.maxRetries ?? 2

    return new QueryClient({
        queryCache: new QueryCache({
            onError: (error, query) => {
                if (query.meta?.suppressToast) return
                // 401s are handled by the axios interceptor (redirect to login).
                if (isProblemDetails(error) && error.status === 401) return
                notify(error)
            },
        }),
        mutationCache: new MutationCache({
            onError: (error, _variables, _context, mutation) => {
                if (mutation.meta?.suppressToast) return
                // 401s are handled by the axios interceptor (redirect to login).
                if (isProblemDetails(error) && error.status === 401) return
                notify(error)
            },
        }),
        defaultOptions: {
            queries: {
                retry: (failureCount: number, error: Error) => {
                    // Don't retry client errors (4xx) — they won't succeed on retry.
                    if (isProblemDetails(error) && error.status < 500)
                        return false
                    return failureCount < maxRetries
                },
            },
        },
    })
}
