import type { ReactNode } from 'react'
import {
    QueryClient,
    QueryClientProvider,
    QueryCache,
    MutationCache,
} from '@tanstack/react-query'
import { showErrorNotification } from './showErrorNotification'
import { isProblemDetails } from './problemDetailsUtils'

let context:
    | {
          queryClient: QueryClient
      }
    | undefined

export function getContext() {
    if (context) {
        return context
    }

    // Error handling for hooks generated by Orval (React Query client).
    // Suppress per-call via `meta: { suppressToast: true }` on useQuery / useMutation.
    // For direct axios calls (not hooks), use `__suppressToast: true` on the request config —
    // see types/axios.d.ts for the typed contract.
    const queryClient = new QueryClient({
        queryCache: new QueryCache({
            onError: (error, query) => {
                if (query.meta?.suppressToast) return
                // 401s are handled by the axios interceptor (redirect to login).
                if (isProblemDetails(error) && error.status === 401) return
                showErrorNotification(error)
            },
        }),
        mutationCache: new MutationCache({
            onError: (error, _variables, _context, mutation) => {
                if (mutation.meta?.suppressToast) return
                // 401s are handled by the axios interceptor (redirect to login).
                if (isProblemDetails(error) && error.status === 401) return
                showErrorNotification(error)
            },
        }),
        defaultOptions: {
            queries: {
                retry: (failureCount: number, error: Error) => {
                    // Don't retry client errors (4xx) — they won't succeed on retry.
                    if (isProblemDetails(error) && error.status < 500)
                        return false
                    return failureCount < 2
                },
            },
        },
    })

    context = {
        queryClient,
    }

    return context
}

export default function TanStackQueryProvider({
    children,
}: {
    children: ReactNode
}) {
    const { queryClient } = getContext()

    return (
        <QueryClientProvider client={queryClient}>
            {children}
        </QueryClientProvider>
    )
}
